site_name: SM2 Wiki
site_description: Wiki for SM2 scholars
site_author: SM2-wiki Team
site_url: https://sm2-wiki.github.io/SM2-wiki/

repo_name: 'SM2-wiki'
repo_url: 'https://github.com/SM2-wiki/SM2-wiki'
edit_uri: 'edit/master/docs/'


copyright: 'Copyright &copy; 2019 SM2-wiki Team'

google_analytics:
  - 'UA-148396512-1'
  - 'auto'
  
nav:

   - 主页:
      - Welcome to SM2 Wiki!: index.md
      - 关于: intro/about.md
      - 如何做出贡献: intro/htc.md
  
theme:
  name: 'material'
  language: 'zh'
  palette:
    primary: 'blue'
    accent: 'red'
  feature:
    tabs: true
  font: 
    text: 'Fira Sans'
    code: 'Roboto Mono'
  
extra:
  #disqus: 'SM2-wiki'
  pagetime: 'on'
  copyright: '<a href="https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh">CC BY-NC-SA 4.0</a>'
  manifest: 'manifest.webmanifest'
  disqus: 'SM2-wiki'
  social:
    - type: github
      link: https://github.com/SM2-wiki
  search:
    language: 'jp'
  
extra_javascript:
 # - '_static/js/extra.js?v=15'
  - '_static/js/jquery-3.2.1.min.js'
  - 'https://cdnjs.loli.net/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-MML-AM_CHTML'

extra_css:
  - _static/css/extra.css


markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: true
      linenums: true
  - toc:
      permalink: true
  - footnotes
  - meta
  - def_list
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_png
      #emoji_generator: !!python/name:pymdownx.emoji.to_svg
      #emoji_generator: !!python/name:pymdownx.emoji.to_png_sprite
      #emoji_generator: !!python/name:pymdownx.emoji.to_svg_sprite
      #emoji_generator: !!python/name:pymdownx.emoji.to_awesome
      #emoji_generator: !!python/name:pymdownx.emoji.to_alt
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.tilde


